site_name: Repository naming convention  # Replace with your project's name
repo_url: https://github.com/reslava/docs-repository-naming-convention/docs # Replace with your repo URL
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - toc.integrate
nav:
  - Home: docs/index.md
  # The rest of the navigation will be generated automatically
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - toc:
      permalink: true
